/**
 * Shared type definitions for the Test Intel pipeline.
 *
 * Each stage of the pipeline operates on well-defined data structures,
 * enabling clean separation of concerns and independent testability.
 */

// ─── Collector Types ───────────────────────────────────────────────

/** Raw result from a single Vitest test assertion */
export interface RawTestResult {
  /** Name of the test (from the `it()` or `test()` block) */
  name: string;
  /** Full suite/file path */
  suiteName: string;
  /** Test status */
  status: 'pass' | 'fail' | 'skip';
  /** Duration in milliseconds */
  duration: number;
  /** Raw error message if the test failed */
  errorMessage?: string;
  /** Raw stack trace string */
  stackTrace?: string;
}

/** Output from the collector module */
export interface CollectorOutput {
  /** Total number of tests found */
  totalTests: number;
  /** Number of passed tests */
  passed: number;
  /** Number of failed tests */
  failed: number;
  /** Number of skipped tests */
  skipped: number;
  /** Array of failing test details */
  failures: RawTestResult[];
  /** Raw Vitest JSON output (for debugging) */
  rawOutput?: string;
}

// ─── Normalizer Types ──────────────────────────────────────────────

/** A single parsed stack frame */
export interface StackFrame {
  /** Function or method name */
  functionName: string;
  /** Source file path */
  filePath: string;
  /** Line number */
  line: number;
  /** Column number */
  column: number;
  /** Whether this frame is from node_modules (noise) */
  isExternal: boolean;
  /** Extracted source code snippet around this line (if available) */
  codeContext?: string;
}

/** Normalized test failure with cleaned data */
export interface NormalizedFailure {
  /** Test name */
  testName: string;
  /** Suite / file path */
  suiteName: string;
  /** Duration in ms */
  duration: number;
  /** Cleaned, human-readable error message */
  errorMessage: string;
  /** Parsed and filtered stack frames (most relevant first) */
  stackFrames: StackFrame[];
  /** Original raw error for reference */
  rawError: string;
  /** Raw expected and actual values extracted from assertion (if any) */
  diff?: { expected: string; actual: string };
}

// ─── Detector Types ────────────────────────────────────────────────

/** Known failure category types */
export type FailureCategory =
  | 'timeout'
  | 'syntax_error'
  | 'type_error'
  | 'runtime_error'
  | 'assertion_failure'
  | 'dependency_error'
  | 'mock_error'
  | 'unhandled_rejection'
  | 'unknown';

/** Confidence level for classification */
export type Confidence = 'high' | 'medium' | 'low';

/** Classification result from the detector */
export interface Classification {
  /** The detected failure category */
  category: FailureCategory;
  /** Confidence level of the classification */
  confidence: Confidence;
  /** Short human-readable reason for the classification */
  reason: string;
  /** Matched keywords / patterns that triggered the classification */
  matchedPatterns: string[];
}

/** A failure enriched with classification data */
export interface ClassifiedFailure extends NormalizedFailure {
  classification: Classification;
}

// ─── Prompt Builder Types ──────────────────────────────────────────

/** Constructed prompt for the LLM */
export interface LLMPrompt {
  /** System instruction for the LLM */
  systemPrompt: string;
  /** User message containing the failure context */
  userPrompt: string;
  /** Estimated token count (rough) */
  estimatedTokens: number;
}

// ─── Explainer Types ───────────────────────────────────────────────

/** AI-generated explanation for a test failure */
export interface Explanation {
  /** Root cause analysis */
  rootCause: string;
  /** Suggested fix(es) */
  suggestedFixes: string[];
  /** Additional context or notes */
  additionalContext?: string;
  /** Whether the explanation was generated by a real LLM or a mock */
  isMock: boolean;
}

/** Full analysis result for a single test failure */
export interface AnalysisResult {
  failure: ClassifiedFailure;
  explanation: Explanation;
}

// ─── Pipeline Config ───────────────────────────────────────────────

/** Runtime configuration for the pipeline */
export interface PipelineConfig {
  /** Path to the test file to analyze */
  testFilePath: string;
  /** Whether real LLM API calls are enabled */
  llmEnabled: boolean;
  /** OpenAI API key (if using real LLM) */
  apiKey?: string;
  /** Whether to show verbose/debug output */
  verbose: boolean;
}
